---
- name: Monitor Fleet Connectivity
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    influx_url: "http://influxdb:8086/write?db=fleet_data"

  tasks:
    - name: Ping every host in the inventory
      shell: "ping -c 1 -W 1 {{ hostvars[item].ansible_host }}"
      loop: "{{ groups['holons'] }}"
      register: ping_results
      ignore_errors: yes
      changed_when: false

    - name: Send Metrics to InfluxDB
      uri:
        url: "{{ influx_url }}"
        method: POST
        # If ping succeeds, extract the time. If it fails, default to 0.
        body: >-
          network_latency,host={{ item.item }} status={{ 1 if item.rc == 0 else 0 }},ping_ms={{ item.stdout | regex_search('time=[0-9.]+') | default('time=0', true) | replace('time=', '') }}
        status_code: 204
      loop: "{{ ping_results.results }}"
      ignore_errors: yes
